-- Integrity constraints Prisma's schema language cannot express.
--
-- Paste this into the migration generated by `prisma migrate dev` before
-- applying it. These are not optional hardening: each one closes a race or
-- an invalid state that application code cannot reliably prevent.

-- ---------------------------------------------------------------------------
-- 1. One ACTIVE enrolment per learner per cohort
-- ---------------------------------------------------------------------------
-- REG-03 requires idempotent processing to yield at most one active
-- enrolment. A plain UNIQUE (userId, cohortId) is wrong: it would block a
-- learner who withdrew from ever re-enrolling. A partial index constrains
-- only the rows that matter.

CREATE UNIQUE INDEX enrolment_one_active_per_learner_cohort
  ON "Enrolment" ("userId", "cohortId")
  WHERE status = 'ACTIVE';

-- ---------------------------------------------------------------------------
-- 2. A Cohort targets exactly one Course XOR one Programme
-- ---------------------------------------------------------------------------
-- COH-01. Prisma has no XOR, so without this a cohort can point at both or
-- neither and every downstream query has to defend against it.

ALTER TABLE "Cohort"
  ADD CONSTRAINT cohort_targets_exactly_one_offer
  CHECK (
    ("courseId" IS NOT NULL AND "programmeId" IS NULL)
    OR
    ("courseId" IS NULL AND "programmeId" IS NOT NULL)
  );

-- ---------------------------------------------------------------------------
-- 3. Cohort capacity cannot be exceeded
-- ---------------------------------------------------------------------------
-- COH-06 requires that concurrent attempts cannot exceed capacity.
--
-- The check constraint below is the backstop. The primary mechanism is
-- application-side and must be used on every path that activates an
-- enrolment:
--
--   BEGIN;
--     SELECT "seatsTaken", capacity FROM "Cohort" WHERE id = $1 FOR UPDATE;
--     -- refuse if seatsTaken >= capacity
--     INSERT INTO "Enrolment" (...);
--     UPDATE "Cohort" SET "seatsTaken" = "seatsTaken" + 1 WHERE id = $1;
--   COMMIT;
--
-- SELECT ... FOR UPDATE serialises concurrent checkouts on the cohort row.
-- Counting enrolments and then inserting loses the race: both transactions
-- read the same count before either writes.

ALTER TABLE "Cohort"
  ADD CONSTRAINT cohort_capacity_not_exceeded
  CHECK ("seatsTaken" >= 0 AND "seatsTaken" <= capacity);

-- ---------------------------------------------------------------------------
-- 4. Money is never negative
-- ---------------------------------------------------------------------------
-- NFR-14. Cheap, and catches a class of bug that is expensive in a payment
-- system.

ALTER TABLE "Order"
  ADD CONSTRAINT order_amount_non_negative CHECK ("amountMinor" >= 0);

ALTER TABLE "PaymentAttempt"
  ADD CONSTRAINT payment_amount_non_negative CHECK ("amountMinor" >= 0);

ALTER TABLE "Refund"
  ADD CONSTRAINT refund_amount_positive CHECK ("amountMinor" > 0);

-- ---------------------------------------------------------------------------
-- 5. Cohort dates are coherent
-- ---------------------------------------------------------------------------
-- COH-02 requires date conflicts to block publication. This makes the
-- impossible ordering unrepresentable rather than merely validated.

ALTER TABLE "Cohort"
  ADD CONSTRAINT cohort_dates_ordered
  CHECK ("endsAt" >= "startsAt" AND "enrolmentClosesAt" >= "enrolmentOpensAt");

-- ---------------------------------------------------------------------------
-- 6. Assignment scope coherence
-- ---------------------------------------------------------------------------
-- RBAC-05. A GLOBAL grant has no scopeId; every narrower grant must have one.
-- Without this, a scoped grant with a null scopeId silently behaves as global.

ALTER TABLE "Assignment"
  ADD CONSTRAINT assignment_scope_id_matches_type
  CHECK (
    ("scopeType" = 'GLOBAL' AND "scopeId" IS NULL)
    OR
    ("scopeType" <> 'GLOBAL' AND "scopeId" IS NOT NULL)
  );
