-- Integrity constraints Prisma's schema language cannot express, Phase 4.
--
-- Paste this into the migration generated by `prisma migrate dev` before
-- applying it. This is not optional hardening: it closes an invalid state
-- that application code cannot reliably prevent.

-- ---------------------------------------------------------------------------
-- 1. A publication payload must always carry its schema marker
-- ---------------------------------------------------------------------------
-- CAT-05/CAT-06. Publishing snapshots the obligation tree as a JSON object
-- (D-02); a scalar or array payload would be a malformed publish that no
-- application code checks for once it reaches the database. Unlike
-- 001_integrity.sql, this constraint has a regression test
-- (tests/schema-catalogue.test.ts) so the manual paste-in cannot silently go
-- unapplied the way 001_integrity.sql's did.

ALTER TABLE "CoursePublication"
  ADD CONSTRAINT course_publication_payload_object
  CHECK (jsonb_typeof("payload"::jsonb) = 'object');

ALTER TABLE "ProgrammePublication"
  ADD CONSTRAINT programme_publication_payload_object
  CHECK (jsonb_typeof("payload"::jsonb) = 'object');
