-- Integrity constraints Prisma's schema language cannot express, Phase 5.
--
-- Paste this into the migration generated by `prisma migrate dev --create-only`
-- before applying it. These are not optional hardening: each one closes an
-- invalid state that application code cannot reliably prevent.
--
-- Like 002_catalogue_integrity.sql, and UNLIKE 001_integrity.sql, every
-- constraint below has a regression test — tests/schema-cohort.test.ts —
-- which asserts the constraint name appears in an applied migration.sql AND
-- that it rejects a bad row against real Postgres. The manual paste-in
-- therefore cannot silently go unapplied the way 001_integrity.sql's did.
--
-- Already applied in prisma/migrations/20260901115332_init/migration.sql and
-- NOT re-created here: enrolment_one_active_per_learner_cohort,
-- cohort_targets_exactly_one_offer, cohort_capacity_not_exceeded,
-- cohort_dates_ordered.

-- ---------------------------------------------------------------------------
-- 1. A cohort's seat-hold TTL is never negative
-- ---------------------------------------------------------------------------
-- D-02. `holdMinutes` is nullable (NULL / 0 both mean "no hold"); a negative
-- TTL is meaningless and would make the sweep window run backwards.

ALTER TABLE "Cohort"
  ADD CONSTRAINT cohort_hold_minutes_non_negative
  CHECK ("holdMinutes" IS NULL OR "holdMinutes" >= 0);

-- ---------------------------------------------------------------------------
-- 2. A transfer never points an enrolment at itself
-- ---------------------------------------------------------------------------
-- D-13. `transferredFromId` records the SOURCE enrolment of a transfer-in; a
-- self-reference is a bug that would corrupt transfer-chain traversal.

ALTER TABLE "Enrolment"
  ADD CONSTRAINT enrolment_transfer_not_self
  CHECK ("transferredFromId" IS NULL OR "transferredFromId" <> "id");

-- ---------------------------------------------------------------------------
-- 3. A seat hold exists only while the enrolment is PENDING_PAYMENT
-- ---------------------------------------------------------------------------
-- D-02/D-03 (RESEARCH Pitfall 3). This makes the seat-held predicate
-- unambiguous: a PENDING_PAYMENT enrolment holds a seat iff holdExpiresAt IS
-- NOT NULL. It therefore obliges every transition OUT of PENDING_PAYMENT
-- (approve, cancel, expire) to null holdExpiresAt in the same write, so
-- seatsTaken can never drift against a stale hold.

ALTER TABLE "Enrolment"
  ADD CONSTRAINT enrolment_hold_expiry_only_when_pending
  CHECK ("holdExpiresAt" IS NULL OR "status" = 'PENDING_PAYMENT');

-- ---------------------------------------------------------------------------
-- 4. An attendance correction always carries its reason
-- ---------------------------------------------------------------------------
-- ATT-03. The mandatory correction reason, enforced at the database, below
-- the application. Either the row has never been corrected (all three
-- correction columns NULL), or it has been corrected and correctionReason is
-- non-blank.

ALTER TABLE "AttendanceRecord"
  ADD CONSTRAINT attendance_correction_has_reason
  CHECK (
    ("correctedAt" IS NULL AND "correctedById" IS NULL AND "correctionReason" IS NULL)
    OR
    ("correctedAt" IS NOT NULL AND length(btrim("correctionReason")) > 0)
  );
