/**
 * ONE-SHOT generator for the schema-1 golden licence vectors (plan 14-02).
 *
 *   npx tsx tests/support/generate-licence-golden-vectors.ts
 *
 * Mints ten vectors with fixed instants under throwaway Ed25519 keys held only
 * in memory, writes them as single-line .lic files plus manifest.json under
 * tests/fixtures/licence/schema-1/, and prints the three public `x` values to
 * paste into DEV_TRUSTED_KEYS (src/server/licence/trust-set.ts). No signing key
 * is ever written anywhere, so the committed vectors can be verified but never
 * re-signed. That is deliberate: they lock the published contract (D-02), and
 * every later change to format.ts must keep passing them.
 *
 * The script REFUSES to run when manifest.json already exists, so the committed
 * vectors are never regenerated by accident (regenerating would also mint new
 * keys that no longer match DEV_TRUSTED_KEYS).
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { createFixtureKey, mintLicence } from "./licence-fixtures";

const OUTPUT_DIR = path.resolve(process.cwd(), "tests/fixtures/licence/schema-1");
const MANIFEST_PATH = path.join(OUTPUT_DIR, "manifest.json");

const GOLDEN_DEPLOYMENT_ID = "golden-deployment-0001";
const GOLDEN_CLIENT = { id: "golden-client-0001", name: "Golden Training Academy" };

type Vector = {
  file: string;
  expect: string;
  mode: "activate" | "runtime";
  description: string;
  raw: string;
};

function main(): void {
  if (existsSync(MANIFEST_PATH)) {
    console.error(
      "Refusing to run: tests/fixtures/licence/schema-1/manifest.json already exists. " +
        "The committed golden vectors lock the published contract and must not be regenerated.",
    );
    process.exit(1);
  }

  const keyA = createFixtureKey("dev-golden-a");
  const keyB = createFixtureKey("dev-golden-b");
  const keyC = createFixtureKey("dev-golden-c");
  const unlisted = createFixtureKey("dev-golden-unlisted");

  const base = {
    issuedAt: "2026-04-01T00:00:00.000Z",
    notBefore: "2026-04-01T00:00:00.000Z",
    expiresAt: "2027-03-31T23:59:59.000Z",
    graceEndsAt: "2027-04-14T23:59:59.000Z",
    client: GOLDEN_CLIENT,
    deploymentId: GOLDEN_DEPLOYMENT_ID,
  };

  const mint = (
    licenceId: string,
    key: typeof keyA,
    payload: Record<string, unknown> = {},
  ): string => mintLicence({ key, payload: { ...base, licenceId, ...payload } }).raw;

  const valid = mint("golden-valid-active", keyA);
  const tampered = (() => {
    const parts = mint("golden-tampered-payload", keyA).split(".");
    const payload = parts[2];
    const index = Math.floor(payload.length / 2);
    parts[2] = `${payload.slice(0, index)}${payload[index] === "A" ? "B" : "A"}${payload.slice(index + 1)}`;
    return parts.join(".");
  })();
  const wrongPrefix = mint("golden-unsupported-prefix", keyA).replace(/^LMS-LIC1\./, "LMS-LIC2.");

  const vectors: Vector[] = [
    {
      file: "valid-active.lic",
      expect: "ok",
      mode: "activate",
      description: "Valid licence, key a, FIXTURE_NOW is inside the term",
      raw: valid,
    },
    {
      file: "valid-grace.lic",
      expect: "ok",
      mode: "activate",
      description: "Valid signature; FIXTURE_NOW falls inside grace (expiry is not evaluated here)",
      raw: mint("golden-valid-grace", keyA, {
        expiresAt: "2026-09-25T12:00:00.000Z",
        graceEndsAt: "2026-10-09T12:00:00.000Z",
      }),
    },
    {
      file: "expired.lic",
      expect: "ok",
      mode: "activate",
      description: "Valid signature; FIXTURE_NOW is after grace (expiry is not evaluated here)",
      raw: mint("golden-expired", keyA, {
        expiresAt: "2026-08-01T00:00:00.000Z",
        graceEndsAt: "2026-08-15T00:00:00.000Z",
      }),
    },
    {
      file: "retired-key.lic",
      expect: "ok",
      mode: "activate",
      description: "Signed by a retired key, which still verifies",
      raw: mint("golden-retired-key", keyB),
    },
    {
      file: "revoked-key.lic",
      expect: "KEY_REVOKED",
      mode: "activate",
      description: "Signed by a revoked key",
      raw: mint("golden-revoked-key", keyC),
    },
    {
      file: "unknown-key.lic",
      expect: "UNKNOWN_KEY",
      mode: "activate",
      description: "Signed by a key that is not in the trust set",
      raw: mint("golden-unknown-key", unlisted),
    },
    {
      file: "wrong-deployment.lic",
      expect: "WRONG_DEPLOYMENT",
      mode: "activate",
      description: "Correctly signed for a different deployment",
      raw: mint("golden-wrong-deployment", keyA, { deploymentId: "other-deployment-0002" }),
    },
    {
      file: "tampered-payload.lic",
      expect: "BAD_SIGNATURE",
      mode: "activate",
      description: "One payload character changed after signing",
      raw: tampered,
    },
    {
      file: "unsupported-prefix.lic",
      expect: "UNSUPPORTED_SCHEMA",
      mode: "activate",
      description: "Envelope prefix LMS-LIC2 with otherwise valid parts",
      raw: wrongPrefix,
    },
    {
      file: "unsupported-schema.lic",
      expect: "UNSUPPORTED_SCHEMA",
      mode: "activate",
      description: "Correctly signed payload with schemaVersion 2",
      raw: mint("golden-unsupported-schema", keyA, { schemaVersion: 2 }),
    },
  ];

  mkdirSync(OUTPUT_DIR, { recursive: true });
  for (const vector of vectors) {
    writeFileSync(path.join(OUTPUT_DIR, vector.file), `${vector.raw}\n`, "utf8");
  }
  const manifest = vectors.map(({ file, expect, mode, description }) => ({
    file,
    expect,
    mode,
    description,
  }));
  writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");

  console.log(`Wrote ${vectors.length} vectors and manifest.json to ${OUTPUT_DIR}`);
  console.log("Paste into DEV_TRUSTED_KEYS in src/server/licence/trust-set.ts:");
  console.log(`  { kid: "${keyA.kid}", x: "${keyA.x}", status: "active" },`);
  console.log(`  { kid: "${keyB.kid}", x: "${keyB.x}", status: "retired" },`);
  console.log(`  { kid: "${keyC.kid}", x: "${keyC.x}", status: "revoked" },`);
  // The private keys go out of scope here and are never written anywhere.
}

main();
